---
abstract: 'extract the environment from a shell after executing commands'
author:
  - 'Diab Jerius, <djerius@cpan.org>'
build_requires:
  Env::Path: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Time::Out: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Shell-GetEnv
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Expect: 0
  File::Spec: 0
  File::Temp: 0
  IO::File: 0
  Storable: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/gpl-3.0.html
version: 0.08_02
